/** Columns shown on Trades page (matches `public.trades`; large JSON omitted). */
export const TRADE_TABLE_COLUMN_KEYS: readonly string[] = [
  "id",
  "created_at",
  "asset",
  "interval_mins",
  "direction",
  "bet_size",
  "entry_odds",
  "odds_up",
  "odds_down",
  "confidence",
  "strategy",
  "status",
  "profit_loss",
  "exit_odds",
  "resolved_at",
  "loss_reason",
  "paper_trade",
  "market_id",
  "agent_votes",
  "window_start",
  "window_end",
  "reasoning",
];
